services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: robotic-itk-web
    networks:
      - web_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.robotic-itk.rule=Host(`robotik.gouhund.my.id`)"
      - "traefik.http.routers.robotic-itk.entrypoints=websecure"
      - "traefik.http.routers.robotic-itk.tls=true"
      - "traefik.http.routers.robotic-itk.tls.certresolver=letsencrypt"
      - "traefik.http.services.robotic-itk.loadbalancer.server.port=80"
      - "traefik.http.routers.robotic-itk-http.rule=Host(`robotik.gouhund.my.id`)"
      - "traefik.http.routers.robotic-itk-http.entrypoints=web"
      - "traefik.http.routers.robotic-itk-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"


networks:
  web_proxy:
    external: true
